### ISSUE TITLE
JavaScript warning for live search

### ISSUE THREAD

**Issue by Dekadinious** [clerkio/clerk-woocommerce#55] opened 2022-11-30 11:07 UTC
We get this warning for live search. It also appears in Clerk logs at clerk.io.

TypeError: Cannot read properties of undefined (reading 'length') at a (https://cdn.clerk.io/clerk.js:6:86427) at l (https://cdn.clerk.io/clerk.js:6:85877) at l (https://cdn.clerk.io/clerk.js:6:85973) at Object.eval (https://cdn.clerk.io/clerk.js:6:85119) at q.value (https://cdn.clerk.io/clerk.js:6:82048) at T.render (https://cdn.clerk.io/clerk.js:6:83375) at C.render

**Comment by Dekadinious** [comment] 2022-11-30 14:50
Let's add to that this one:

(function () {
	var clerk_no_productids = [];
	Clerk('cart', 'set', clerk_no_productids);
})();

Clerk is not defined on thank you page.

**Comment by FoulBachelor** [comment] 2022-11-30 14:53
What is the name of the store in question in my.clerk.io, would like to have a look at the logs. :)

**Comment by Dekadinious** [comment] 2022-12-01 08:31
Sent you an email :)

**Comment by FoulBachelor** [comment] 2022-12-01 08:44
Didn't get anything on abs@clerk.io, or the github inbox yet. If you send it to abs@clerk.io it should land with me though. 

Thanks in advance!

**Comment by FoulBachelor** [comment] 2022-12-01 09:25
Suggestions warning is due to suggestions not being enabled in your module settings, but being used in the liquid in the design. So the issue for this is not really the module, but rather the mismatch between suggestions being referenced in your liquid template, while actually having the setting turned on to query the suggestions endpoint for live-search.

You can fix this in 3 main ways:

1. Guard the comparison in the design:
{% if suggestions.length %}
   {% if suggestions.length > 0 %}

   {% endif %}
{% endif %}
2. Enable suggestions in the settings in the admin, so the data is present when the template is trying to use it.
3. Delete / Liquid comment the parts that have to do with suggestions if you intend to not use them.

The other issue with Clerk not being defined for the thankyou page, seems to be that it is defined, but often after the self executing function tries to run. 

https://github.com/clerkio/clerk-woocommerce/commit/a3312ada97f15083585dc070950ddecc8d42c3d0

The change to the basket clear timing will be included in the future module release, but the live search warnings are caused by template currently in use + settings in module. I hope this helps. :)

**Closed by FoulBachelor** 2022-12-01 09:25 UTC
